apiVersion: apps/v1
kind: Deployment
metadata:
  name: navya-banking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-and-mongodb 
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: app-and-mongodb
        image: navyasree09/login-app:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          value: "mongodb://navya-banking-service:27017/banking"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017